Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |vb|
    vb.name = "desafio_ansible"
    vb.memory = 1024
    vb.cpus = 2
  end

  config.vm.box = "ubuntu/focal64"

  config.vm.network "public_network", ip: "192.168.0.55",  bridge: "Realtek PCIe GbE Family Controller"
  config.vm.synced_folder "ansible", "/tmp/ansible"
  config.vm.synced_folder "site/", "/var/www/html"

  config.vm.provision "shell", inline: <<-SHELL
  #  apt-get update
    sudo apt install ansible -y
    ansible-playbook --connection=local /tmp/ansible/playbook.yml
  SHELL
end
