Vagrant.configure("2") do |config|
	config.vm.provider "virtualbox" do |vb|
	  vb.name = "primeira_maquina"
	  vb.memory = 1024
	  vb.cpus = 2 # Win11 requer min de 2 cpus
	end

   config.vm.box = "ubuntu/focal64"

end
