Vagrant.configure("2") do |config|
	config.vm.provider "virtualbox" do |vb|
	  vb.name = "segunda_maquina"
	  vb.memory = 2048
	  vb.cpus = 2
	end

   config.vm.box = "ubuntu/focal64"
   
   config.vm.provision "shell", path: "script.sh"
   
end
