Vagrant.configure("2") do |config|
	config.vm.provider "virtualbox" do |vb|
	  vb.name = "terceira_maquina"
	  vb.memory = 2048
	  vb.cpus = 2
	end

  config.vm.box = "ubuntu/focal64"
  config.vm.network "forwarded_port", guest: 80, host: 8090
  config.vm.network "public_network", ip: "192.168.0.56"
  config.vm.provision "shell", path: "script.sh"
  config.vm.synced_folder "site/", "/var/www/html"
  config.vm.synced_folder "ansible/", "/tmp/ansible"
   
  config.vm.provision "shell", inline: <<-SHELL
    ansible-playbook --connection=local /tmp/ansible/playbook.yml
  SHELL
end